board: st: Fix compilation issue
This patch solves a STM32MP2 compilation issue in
board/st/common/stm32mp_fwu.c when CONFIG_FWU_MULTI_BANK_UPDATE
is activated :
    - error: ‘TAMP_FWU_BOOT_INFO_REG’ undeclared
    - error: ‘TAMP_FWU_BOOT_IDX_OFFSET’ undeclared
    - error: ‘TAMP_FWU_BOOT_IDX_MASK’ undeclared
    - error: implicit declaration of function ‘env_set’

Fixes: 4369c6a05035 ("board: st: factorize STM32MP FWU multi-bank support")
Signed-off-by: Patrick Delaunay <patrick.delaunay@foss.st.com>
Signed-off-by: Patrice Chotard <patrice.chotard@foss.st.com>
Reviewed-by: Patrick Delaunay <patrick.delaunay@foss.st.com>