usb: r8a66597: Fix argument mistake of inl
Fail in build, because argument of inl used in r8a66597_read_fifo is wrong.

r8a66597.h:441:35: error: macro "inl" passed 2 arguments, but takes just 1
In file included from r8a66597-hcd.c:25:
r8a66597.h: In function ‘r8a66597_read_fifo’:
r8a66597.h:441: error: ‘inl’ undeclared (first use in this function)
r8a66597.h:441: error: (Each undeclared identifier is reported only once
r8a66597.h:441: error: for each function it appears in.)

Signed-off-by: Nobuhiro Iwamatsu <iwamatsu@nigauri.org>