[MIPS] Update asm string header
This patches contains several bugfixes and cleanups in the latest upstream:

 - Don't include linux/config.h
 - Remove buggy inline version of memscan.
 - Merge with Linux 2.6.11-rc3.
 - Fix undefined reference to strcpy in binfmt_misc caused by gcc 3.4.
 - Goodbye mips64.  31704 lines of code bite the dust.
 - Replace extern inline with static inline.
 - Fix return value of strncpy.
 - Remove a bunch more "$1" clobbers.

Signed-off-by: Shinya Kuribayashi <shinya.kuribayashi@necel.com>