arm64: zynqmp: Add missing maximum-speed property to usb nodes
Add missing properties to dt node.

Error log:
ERROR: usb maximum-speed not found

Signed-off-by: Michal Simek <michal.simek@xilinx.com>