arm: qcom: Update ipq5424-rdp466-u-boot.dtsi for v7.1-dts changes
Once we move to the v7.0-dts tag, we get a failure to build of:
dts/upstream/src/arm64/qcom/ipq5424.dtsi:556.21-573.5: ERROR (phandle_references): /soc@0/mmc@7804000: Reference to non-existent node or label "sdc_default_state"

  also defined at arch/arm/dts/ipq5424-rdp466-u-boot.dtsi:20.8-39.4
ERROR: Input tree has errors, aborting (use -f to force output)

Looking over the changes, this appears to be what's required to keep the
platform functioning as expected.

Acked-by: Casey Connolly <casey.connolly@linaro.org>
Signed-off-by: Tom Rini <trini@konsulko.com>