spi: Add declaration for spi_flash_cmd_bp_unlock
This patch removes compilation warning:
+../drivers/mtd/spi/sf_probe.c: In function
'spi_flash_validate_params':
+../drivers/mtd/spi/sf_probe.c:402:3: warning: implicit declaration of
function 'spi_flash_cmd_bp_unlock' [-Wimplicit-function-declaration]

Also add missing flash parameter:
+../drivers/mtd/spi/sf_probe.c: In function 'spi_flash_validate_params':
+../drivers/mtd/spi/sf_probe.c:402:3: error: too few arguments to
function 'spi_flash_cmd_bp_unlock'
+   ret = spi_flash_cmd_bp_unlock();

Signed-off-by: Michal Simek <michal.simek@xilinx.com>