phy: ti: Add missing function declaration to phy.h
Fix compilation warning:
drivers/net/phy/phy.c: In function ‘phy_init’:
drivers/net/phy/phy.c:488:2: warning: implicit declaration of function
‘phy_ti_init’ [-Wimplicit-function-declaration]
  phy_ti_init();
  ^

Signed-off-by: Michal Simek <michal.simek@xilinx.com>