xilinx: common: Fix compilation error when CONFIG_NET disabled
eth_env_set_enetaddr_by_index() depends on CONFIG_NET which is not cover in
the code. That's why when CONFIG_NET is disabled the following compilation
error is seen:
common/board.c:396: undefined reference to `eth_env_set_enetaddr_by_index' 

Signed-off-by: Michal Simek <michal.simek@xilinx.com>